### ISSUE TITLE
Line break on non-wide windows

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#115]
When a test is presented the following three elements are presented on the same line:

* Test number, e.g. 'Test # 8'
* Domain name tested, e.g. 'nic.vermögensberatung'
* Four boxes, buttons:
  - "History"
  - "Export"
  - "Share"
  - "Settings"

If the domain namn is long or if the language is not English, especially if it is French or Danish, the line is broken in an ugly way. Also depending on window width. I suggests that the four boxes are displayed on a line above, but still to the right, to avoid line breaks.

![image](https://user-images.githubusercontent.com/5430733/79852749-5cfc7180-83c7-11ea-84ac-abc5e5bd37fe.png)

![image](https://user-images.githubusercontent.com/5430733/79852815-769db900-83c7-11ea-8622-3a71e62e8815.png)

![image](https://user-images.githubusercontent.com/5430733/79852873-90d79700-83c7-11ea-8a47-89f4c99a38a8.png)

![image](https://user-images.githubusercontent.com/5430733/79852933-a6e55780-83c7-11ea-9f07-a86b443b25ed.png)

**Comment by pnax** [comment]
Resolved with #263
