### ISSUE TITLE
Change default on displayed message levels

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#118]
Today, the GUI will display messages on levels by default, from INFO to CRITICAL. In most cases the high number of messages on INFO level will hide other messages, and for most users INFO messages are probably not in focus. I suggest that the default is changed so that INFO messages are only shown when they have been selected.

The CLI shows NOTICE and higher by default.

Updated 2022-01-25:

Since the messages are not shown by default the in the current design, instead the levels (Basic, DNSSEC etc) are shown, and those display the severity level by color of the message in the level with the highest severity level, it is an acceptable work-around that the messages are sorted by severity level with the highest level highest per level (Basic, DNSSEC etc).

**Comment by pamasse** [comment]
You suggest showing only NOTICE/WARNING/ERROR/CRITICAL messages and not ALL ?
Basically, it's like selecting only the NOTICE/WARNING/ERROR/CRITICAL filter button?

**Comment by matsduf** [comment]
Yes.
Yes. I suggest that to be the default, but not now. This is a proposal for v2020.1.

**Comment by matsduf** [comment]
Resolved by #297
