### ISSUE TITLE
Wrong link in notice box

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#147]
When opening the «Options» box, a notice appears with the following link :

`What is an undelegated domain test? -> https://zonemaster.fr/faq#undelegated`

However the FAQ page is using a numeric anchor system. I think the link should be https://zonemaster.fr/faq#q12.

**Comment by pamasse** [comment]
The link works so why do you want to change it?

**Comment by pnax** [comment]
I forgot to mention that I am using the English version.

It looks like the links are not consistent between languages :

English : `12. [What is an undelegated domain test?](#q12)`
French : `12. [C'est quoi un test sur un domaine non délégué?](#undelegated)`
Danish : `12. [Hvad er en "ikke-delegeret" test?](#undelegated)`
Swedish : `12. [Vad är ett odelegerat domäntest?](#q12)`

Which one should be kept ?

**Comment by pamasse** [comment]
I prefer explicit links, so I would keep "undelegated"

**Comment by mattias-p** [comment]
I can reproduce this. https://zonemaster.fr/faq#undelegated doesn't work for me, but https://zonemaster.fr/faq#q12 does.

**Comment by matsduf** [comment]
The links with "#undelegated" are incorrect. They should be with "#q12" because that is how it is defined in the Markdown/HTML code.

**Comment by matsduf** [comment]
Fixed by #148.

**Comment by pnax** [comment]
> They should be with "#q12" because that is how it is defined in the Markdown/HTML code.

Well... what should we keep ? `q12` or `undelegated` ?

I just updated the PR #148 with `undelegated` in the `docs/FAQ` files. If we keep this and follow https://github.com/zonemaster/zonemaster-gui/issues/147#issuecomment-718911564 we should also update the other `q1`, `q2` ... `q13` links. I was planning to open a new issue for that, but I feel we should decide first what we keep here.

**Comment by sandoche2k** [comment]
@pnax @matsduf so what is the final decision?

**Comment by pnax** [comment]
I decided to go with `q12` in order to be consistent with the other section anchors. This has been resolved in #148 (merging commit 207b3fa).
If we want to use explicit link, there is an issue to « Clean up or rewrite FAQ » #105, maybe this should be done there.
