### ISSUE TITLE
UX/UI Color contrast for results table

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#150]
In the result table, the current blue background color `#007bff` makes it hard to read the content of the cell written in black.

Is it possible to use better contrast between text color and background color ?

**Comment by matsduf** [comment]
Excedo has installed Zonemaster with some customization. Take a look at that. https://zonemaster.excedonet.net/domain_check

**Comment by pnax** [comment]
Resolved with #236
