### ISSUE TITLE
Draw up a color scheme

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#153]
Today the use of colors in the UI is quite undisciplined. For example, I can find four visual elements on the results page that use some tone of blue. Among them they use three different tones of blue, and the tones don't particularly fit together. Moreover, as pointed out in #150, the blue background color in the test results make them hard to read. And that's just the blues. I have complaints for the other colors too.

We should have a proper color scheme drawn up and documented for Zonemaster GUI. Then we should stick to that color scheme for all visual elements in the UI.

**Comment by pnax** [comment]
From https://github.com/zonemaster/zonemaster-gui/issues/150#issuecomment-779855697, and the link to the Excedo GUI, I have made some screenshots to compare both GUIs. I am not an UX/UI designer but I feel that Excedo's GUI is sober and hence more accessible.

I think that :

1. we should remove the background color in the array and use a similar approach than Excedo and use colors as an addition to the text
2. as stated in this issue, we should use less colors, or stick the colors to the results, so I would suggest to use the same color for all buttons `History`, `Export`, `Share` and `Settings` (as done by Excedo)
3. we should rethink which color we use for what and document that
4. we should use better contrast when the text is written with a background color


@matsduf @mattias-p any thoughts on this ?


## Screenshots

### The result array

Zonemaster
![zm-results](https://user-images.githubusercontent.com/70589067/112961841-07d3ee80-9146-11eb-9f69-2c17caa4a21c.png)
Excedo
![excedo-results](https://user-images.githubusercontent.com/70589067/112961828-060a2b00-9146-11eb-8ddd-7dead10d3cdf.png)


### The filter buttons

Zonemaster
![zm-filters](https://user-images.githubusercontent.com/70589067/112961834-073b5800-9146-11eb-8648-6a7feebfaa60.png)
Excedo
![excedo-filters](https://user-images.githubusercontent.com/70589067/112961825-04d8fe00-9146-11eb-9e35-9ac8b09a7d51.png)

### INFO:

Zonemaster
![zm-info](https://user-images.githubusercontent.com/70589067/112961836-073b5800-9146-11eb-9d41-d09a57db3c33.png)
Excedo
![excedo-info](https://user-images.githubusercontent.com/70589067/112961826-05719480-9146-11eb-9506-c6b4d273dad6.png)

### NOTICE:

Zonemaster
![zm-notice](https://user-images.githubusercontent.com/70589067/112961838-07d3ee80-9146-11eb-9446-8d186cafd4e5.png)
Excedo
![excedo-notice](https://user-images.githubusercontent.com/70589067/112961827-05719480-9146-11eb-952c-00b5a7f0d814.png)


### WARNING:

Zonemaster
![zm-warning](https://user-images.githubusercontent.com/70589067/112961844-086c8500-9146-11eb-8e3f-5cf53b312512.png)
Excedo
![excedo-warning](https://user-images.githubusercontent.com/70589067/112961829-06a2c180-9146-11eb-95cc-06263d83dfa3.png)


### ERROR:

Zonemaster
![zm-error](https://user-images.githubusercontent.com/70589067/112961831-06a2c180-9146-11eb-815d-e80763d55187.png)
Excedo
![excedo-error](https://user-images.githubusercontent.com/70589067/112961822-04406780-9146-11eb-90f1-4e51b702a4a3.png)


## Colors

The values extracted from both GUIs :

| element | Excedo | Zonemaster |
| --- | --- | --- |
| button history | `#6c757d` | `#ffc107` |
| button export | `#6c757d` | `#17a2b8` |
| button share | `#6c757d` | `#28a745` |
| button settings | |  `#6c757d` |
| button contact | `#6c757d` | |
| result all | `#68ad54` | `#007bff` |
| result info | `#68ad54` | `#007bff` |
| result notice | `#017add` | `#fff638` |
| result warning | `#e0d20e` | `#ff9019` |
| result error | `#e41700` | `#dc3545` |
| result critical | `#e41700` | `#dc3545` |

**Comment by pnax** [comment]
Working a little bit on this, I came up with the following proposal :

| Level | color |
| --- | --- |
| INFO | `#66ad54` |
| NOTICE | `#007bff` |
| WARNING | `#ff9019` |
| ERROR | `#ec3545` |
| CRITICAL | `#ec3545` |

![zm-GUI-results](https://user-images.githubusercontent.com/70589067/113159492-ee619e00-923c-11eb-80ee-ea70cb077e31.png)
![zm-GUI-filters](https://user-images.githubusercontent.com/70589067/113159482-ec97da80-923c-11eb-9456-41d0f2bb14a5.png)
![zm-GUI-group](https://user-images.githubusercontent.com/70589067/113159485-ed307100-923c-11eb-9229-27de662986f6.png)
![zm-GUI-nogroup](https://user-images.githubusercontent.com/70589067/113159491-edc90780-923c-11eb-8313-11221e3e4980.png)

**Comment by matsduf** [comment]
This issue has been resolved by #263.
