### ISSUE TITLE
GUI fails with MariaDB as the backend - Internal Server Error (CentOS 7)

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-gui#155]
The test machine is here : http://vps804922.ovh.net/domain_check

The backend post sanity check works and all the backend status are OK

**Comment by sandoche2k** [comment]
http://vps323914.ovh.net/domain_check for PostgreSQL

**Comment by matsduf** [comment]
Both links indicated that GUI does not have contact with backend. But if you try directly against backend, what happens then? CentOS 7 or 8?

**Comment by sandoche2k** [comment]
As mentioned earlier, the post sanity check for the Backend is OK

**Comment by sandoche2k** [comment]
Don't have any issue in CentOS 8 : http://vps803736.ovh.net/domain_check

**Comment by matsduf** [comment]
If you let the GUI on CentOS 7 go against the backend on CentOS 8, and vice versa, what happens? Of course, you have to open backend for the external IP address.

**Comment by pnax** [comment]
Anything relevant in `/var/log/zonemaster/zonemaster-web-gui-error.log` ?

**Comment by sandoche2k** [comment]
The cause for the error : https://confluence.atlassian.com/bitbucketserverkb/permission-denied-in-apache-logs-when-used-as-a-reverse-proxy-790957647.html

Solved and closing
