### ISSUE TITLE
Typos in french "présentation"

### ISSUE THREAD

**Issue by vlevigneron** [zonemaster/zonemaster-gui#17]
`A propos de...` => `À propos de...` (twice)
`du fonctionnement du système de noms de domaine DNS` => `du fonctionnement du système de noms de domaine, le DNS`
`en examinant DNS de la racine (.) Vers le TLD` => `en examinant le DNS de la racine (.) vers le TLD`
Pehaps we should find a better way to say that  `Par conséquent, DNS a été développé un système supplémentaire pour nous quand nous voulons atteindre un serveur web sur un site spécifique ou un serveur de messagerie auquel nous voulons envoyer un email.`

**Comment by sandoche2k** [comment]
@pamasse close?
