### ISSUE TITLE
Better error message for validation errors

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#177]
When you press "Check" to check a domain name, a start_domain_test request is sent to the Backend. If an error response is returned, the message "Internal server error" is displayed. If the error response is due to invalid input submitted by the user, the displayed message is still "Internal server error". This is not helpful to the user.

It would be better if the GUI inspected the error code and displayed a different message if the error is caused by invalid inputs.

**Comment by blacksponge** [comment]
resolved by #230
