### ISSUE TITLE
Logotype does not display correctly on Chrome (and Chromium)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#181]
When Zonemaster-GUI is opened the Zonemaster logotype with built-in Afnic and Internetstiftelsen logotypes appear in top left. That works with Firefox and Safari, but it does not work with Chrome.

## Screenshot from Firefox:
![logo-is-displayed-by-Firefox](https://user-images.githubusercontent.com/5430733/107759551-c4095f00-6d28-11eb-8505-fc1eeea6909f.png)

## Screenshot from Chrome:
![logo-is-not-displayed-by-chrome](https://user-images.githubusercontent.com/5430733/107759600-d4b9d500-6d28-11eb-9d7d-86e1028e7175.png)

**Comment by pamasse** [comment]
Try with a PNG image sized 250x63px

**Comment by matsduf** [comment]
#187 resolves this issue.

**Comment by pnax** [comment]
Just to inform you that I have made a quick fix few days ago on zonemaster.net. The logo might appear on Chrome now.

**Comment by matsduf** [comment]
That is good.
