### ISSUE TITLE
Date format in history view

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#189]
Today the history view uses a date format that looks like this "3/19/21, 6:36 PM GMT+1". We should use ISO 8601 (with a SPACE instead of the T).

More precisely the format `YYYY-mm-dd HH:MM±hhmm` should be used.

**Comment by matsduf** [comment]
This date-time stamp is for human consumption. I support the suggestion, and I suggest that we limit it to minutes, i.e. not seconds. 

A second question is time zone. One possibility is to have UTC only, another would have a configuration setting that sets the time zone. In both cases I think the time zone should be explicitly stated.

Today there is a time zone specification, but that is wrong. I executed at test at zonemaster.net at 14.05 UTC, and when the test is displayed it says "March 22, 2021 3:05 PM" without time zone, but in the history list "3/22/21, 2:05 PM GMT+1" which is 13.05 UTC.

If the browser signals time zone -- does it? -- then using that would be useful for the users. Still it should explicitly state the time zone.

**Comment by mattias-p** [comment]
The exact format your suggesting is `YYYY-mm-dd HH:MM±hhmm`, right? I updated the description to that effect.

If you're getting the wrong date reported back to you that deserves a dedicated bug report.

I'm not familiar with the framework we're using for the GUI, but it looks to me like the time zone being used is whatever the client has configured as local time.

**Comment by matsduf** [comment]
It is a standard, but is that a user friendly way of show time zone? Is it obvious for most people how `±hhmm` should be interpreted?

**Comment by mattias-p** [comment]
I would say `YYYY-mm-dd HH:MM` is by far the most user friendly format. It's unambiguous with regard to field order. You can quickly get a sense of the distance between two adjacent dates.

So what are you suggesting?

**Comment by matsduf** [comment]
I agree with you, `YYYY-mm-dd HH:MM` is very clear and user friendly. I was thinking of and discussing the time zone. `±hhmm` is not crystal clear.

**Comment by mattias-p** [comment]
Ok, I get it. So how do you suggest we go forward?

**Comment by matsduf** [comment]
The issue has been created, and now we have to see who can provide a solution.

**Comment by pnax** [comment]
I agree with the proposal. I think we can use UTC for all displayed dates in the GUI.
And some pointers to the documentation :

**Comment by pnax** [comment]
Closed by #191
