### ISSUE TITLE
Since upgrading to 3.2.2, english version of front page shows some placeholders

### ISSUE THREAD

**Issue by mfld-pub** [zonemaster/zonemaster-gui#193]
Fr | Sv | Da  are OK but en shows:

![zmd](https://user-images.githubusercontent.com/66289900/114267376-5aa28580-9a25-11eb-930d-567051916212.JPG)

I checked /var/www/html/zonemaster-web-gui/dist/assets/i18n/en.json and it seems OK.

**"ABOUT_ZONEMASTER_TEXT"**
and 
**"ABOUT_DNS_TEXT"** are defined:

```
{
        "ABOUT_DNS_TEXT": "Most people who use the internet have never reflected over what actually happens when one types an address in their web browser and then clicks the enter button. To simplify, the domain name system, (DNS) is a database that associates domain names to IP addresses, the same way a phone book associates names to phone numbers. An IP address is a unique series of numbers that identifies every computer that is connected to the internet. It’s similar to the way every telephone has its own number in the telephone network. A long series of numbers works fine for computers, but it’s difficult for people to memorize. Therefore, DNS has been developed an extra system for us when we want to reach a web server on a specific site or an email server we want to send an email to. ",
        "About Zonemaster": "About Zonemaster",
        "ABOUT_ZONEMASTER_TEXT": "Give your domain a complete physical! Zonemaster helps you to control how your website is doing. As a bonus, you also get a better understanding of how the domain name system, DNS, works. When a domain (also called zone) is sent to Zonemaster, the program investigates the state of the domain from beginning to end. This is done through Zonemaster examining DNS from the root (.) to the TLD (top-level domain, for example, .se), and then finally through the DNS servers that contain information about the specified domain (for example, zonemaster.se). Zonemaster is also able to perform many other tests, for example, checking the DNSSEC signatures, that different hosts can be accessed and that the IP addresses are valid. This is all to make sure that your domain runs as good as possible",
        "About domain name system, DNS": "About domain name system, DNS",
```

**Comment by matsduf** [comment]
@mfld-pub, thank you for your report. However, I cannot replicate the problem. When I test with both Firefox and Chrome I get the expected text.

* The screen shot you show, is not from https://zonemaster.net/, is it? Can you check how it looks lite when you test that?
* Have you done the installation? Is that done according to the installation instructions using the v3.2.2 Zonemaster-GUI-package [zonemaster_web_gui.zip].
* What web browser do you use?

[zonemaster_web_gui.zip]: https://github.com/zonemaster/zonemaster-gui/releases/download/v3.2.2/zonemaster_web_gui.zip

**Comment by matsduf** [comment]
@mfld-pub, do you have more information?

**Comment by mfld-pub** [comment]
Update:

It was occuring in Firefox, Brave, Chrome and Edge after upgrading from 3.2.0 to 3.2.2 following the instructions (and upgrading the underlying engine and backend to latest first).

I rolled back by unzipping 3.2.0 and overwriting. Then I unzipped 3.2.2 again and now the issue is resolved. 

Very strange. I either skipped an overwrite somewhere during the initial upgrade/unzip or something else went wrong. It was only EN the other languages were fine. In any case, I re-did the upgrade and now I am on 3.2.2 and all is well in all locales.

**Comment by matsduf** [comment]
@mfld-pub, good to hear that you could resolve the issue. It is always a little bit frustrating when you do not understand why. And thank you for sharing your experience.

I am interested in hearing what kind of installation this is. Is this local installation for your own use, for a smaller group or is this available for general users. If you are willing to share, it would be great, either here or direct email to me. You will find my email adress mildly encode in my [profile](https://github.com/matsduf).
