### ISSUE TITLE
Convert domain names to ASCII

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#197]
Domain names should be converted to ASCII before they're sent them to the RPCAPI.

**Comment by matsduf** [comment]
Or rather, all IDN labels should be converted to A-labels according to IDNA2008.

IDNA2008 does not accept U-labels with upper-case letters, e.g.  the first label of `Räksmörgås.se` is not a valid U-label according to IDNA2008. Neither is `RÄKSMÖRGÅS` etc. I think it is reasonable to have a pre-process where all upper-case letters, following the Unicode database definition, are down-cased to their lower-case letters before the "to-ascii" conversion to A-label. That pre-process should be applied to all labels, also to ascii labels to make the input consistent.

**Comment by pnax** [comment]
Documenting libraries that might help to perform the conversion:
* [idna-uts46](https://github.com/jcranmer/idna-uts46)
* [IdnaJS](https://github.com/peteroupc/IdnaJS)

**Comment by matsduf** [comment]
This relates to https://github.com/zonemaster/zonemaster/pull/942 (Basic00). We should have a specification before we implement.

**Comment by pnax** [comment]
Thinking about this issue, I can't recall why we choose to do this conversion on the client side. Why not letting the Backend do the conversion (and even have and API method for that)?

**Comment by matsduf** [comment]
It is more than conversion to ASCII representation. It is to convert to a normalized form (see [proposed Basic00]) to make sure that test history shows all instances that a domain name has been tested independent how it was written. It is not only about the zone name, but also about name server names (see [proposed Basic00]).

If we let Backend do the normalization, then we have to reimplement that in CLI too. It think it would be better to implement the normalization in Engine. GUI does not have direct access to Engine, but it could be possible to let Backend have a method for domain name normalization. GUI could, as a preprocess, send the raw domain name to that method, and Backend could use Engine code to normalize and return the domain name in its normalized form. To protect the RPCAPI from problematic characters, the normalization method could require that the domain name is submitted Base64 encoded.

[proposed Basic00]: https://github.com/zonemaster/zonemaster/pull/942

**Comment by pnax** [comment]
You are right. By Backend I meant reusing in the Backend an Engine method (such as Basic00) and exposing it via the API. So it seems we agree on the implementation here :)

> To protect the RPCAPI from problematic characters, the normalization method could require that the domain name is submitted Base64 encoded.

Good remark, I would not have thought about a potential issue here.

**Comment by mattias-p** [comment]
> To protect the RPCAPI from problematic characters, the normalization method could require that the domain name is submitted Base64 encoded.

What additional protection does base64 give?

**Comment by matsduf** [comment]
> What additional protection does base64 give?

The idea is that the JSON for the RPC API only contains safe characters.

**Comment by mattias-p** [comment]
The JSON is already UTF-8. Isn't that enough to be safe?

**Comment by matsduf** [comment]
> The JSON is already UTF-8. Isn't that enough to be safe?

I might be so. I think the start is the [proposed Basic00]. 

[proposed Basic00]: https://github.com/zonemaster/zonemaster/pull/942

**Comment by blacksponge** [comment]
Is this still relevant now that normalization of domains is implemented in backend (using the engine provided method) ?

**Comment by matsduf** [comment]
The problem behind the issue has been resolved. It can be closed.
