### ISSUE TITLE
Disclose testid on result page

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#203]
Today when you run a test and it completes your browser stay at the `/domain_check` URL and the testid isn't shown anywhere on the page.

It'd be nice if the address bar was updated so you could just copy the address to share the result.

It would also be nice it was easy to copy just the testid. I just ran a test of a domain through the GUI and another one of the same domain through zmtest. I noticed that the testid wasn't reused so I wanted to use `zmb get_test_params` to see what might be different, but the testid wasn't readily available.

**Comment by matsduf** [comment]
If you press the "share" button you will get a URL with hash test ID to share. The non-hash test ID is shown directory, but that is not very useful. Should that be replaced by the hash test ID?

<img width="942" alt="image" src="https://user-images.githubusercontent.com/5430733/119979838-bddb7d80-bfbb-11eb-923d-808dc12edb2f.png">

**Comment by mattias-p** [comment]
Ah! I guess I usually try to stay away from share buttons :) Technically that's a solution to my problem.

Both the test id and the link need to be available. I think that's perfectly sufficient if the test id is shown as part of the link. If you know what to do with a test id and see the URL, you'll know how to take out the test id from the URL.

I think we should have a UX savvy person do a makeover of the UI.

**Comment by matsduf** [comment]
> Ah! I guess I usually try to stay away from share buttons :)

They usually make all your personal data being shared by evil companies. :-)

> I think we should have a UX savvy person do a makeover of the UI.

Yes, but that is a different issue, isn't it?

**Comment by mattias-p** [comment]
> Yes, but that is a different issue, isn't it?

Yeah I guess. I'm closing this.
