### ISSUE TITLE
Travis fails

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#210]
Since recently Travis is failing. It might be because of the Chromedriver that uses a new version of Chrome.
See PR #207 where this has been discovered, especially these comments https://github.com/zonemaster/zonemaster-gui/pull/207#issuecomment-853144960 and https://github.com/zonemaster/zonemaster-gui/pull/207#issuecomment-853152984

Maybe the error is somewhere else... I have not much clue for now, but it would be nice to see Travis happy again ;)

**Comment by matsduf** [comment]
@pamasse, is it OK to assign you this?

**Comment by matsduf** [comment]
@blacksponge, could you take a look at this issue to see if you can find out anything?

**Comment by blacksponge** [comment]
As @pnax stated it in the PR, it seems to come from the Chrome upgrade, there is an on going issue at protractor ( https://github.com/angular/protractor/issues/5519 ). I've downgraded the webdriver to chrome 90 to test locally and it seems to fix most of the issue, I'll do a PR soon.

**Comment by blacksponge** [comment]
Closing this as the upstream issue has been fixed. Travis config updated in #254
