### ISSUE TITLE
Make selected language stick out

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#212]
When starting the GUI, the right corner has the language selection (here I disregard narrow windows):

<img width="236" alt="image" src="https://user-images.githubusercontent.com/5430733/120822962-3495ef00-c557-11eb-92b7-b5eae0554db6.png">

You cannot see what language has been selected. Make the selected language stick out. It could be a combination of increasing the size of the letters, making the letters bold face, changing the backround or something else.

**Comment by blacksponge** [comment]
resolved by #222
