### ISSUE TITLE
Add full language at "mouse over"

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#213]
When starting the GUI, the right corner has the language selection (here I disregard narrow windows):

<img width="236" alt="image" src="https://user-images.githubusercontent.com/5430733/120823462-bede5300-c557-11eb-882a-5d9f54ffcfb4.png">

Add the full language name when the mouse is moved over the language code.

**Comment by blacksponge** [comment]
resolved by #222
