### ISSUE TITLE
Missing lead text in the DS sub form

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#226]
When entering DS records there is not lead text for the DNSKEY algorithm and digest type fields, respectively (field 2 and 3):

<img width="983" alt="image" src="https://user-images.githubusercontent.com/5430733/122060311-c1f60080-cded-11eb-9861-f5542d8d440f.png">

But the code says, on lines 122 and 137 states lead text that is not shown:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/5430733/122060963-5ceeda80-cdee-11eb-858c-3dfc3c251adf.png">

**Comment by matsduf** [comment]
@blacksponge, do you see why the lead text is not shown?

**Comment by blacksponge** [comment]
From I have seen, it is because the default value in `digestFormConfig` was the empty string and not `-1` as it is on the select, see #227.

**Comment by matsduf** [comment]
Resolved by #227.
