### ISSUE TITLE
Remember the selected language

### ISSUE THREAD

**Issue by blacksponge** [zonemaster/zonemaster-gui#229]
Currently if I select a language and reload the page, it is back to the default language. Same thing if I close the tab and come back later. It would be better if the language was stored (for instance in local storage) and restored in subsequent visit.

**Comment by matsduf** [comment]
When the GUI is loaded it will look for your default language setting. So if that is fr_FR then you will get i in French. If the language does not match any of the Zonemaster languages, then you will get i in the default language (English). That should work for most users, I guess. I think we should avoid setting any cookies.

**Comment by blacksponge** [comment]
> That should work for most users, I guess.

Since we are offering a language selection menu, I think that for it to work correctly the user should not have to change their language each time they open the website.

> I think we should avoid setting any cookies.

Yes that's why I am talking about local storage, we don't need to send that info to the backend.

**Comment by blacksponge** [comment]
resolved by #235
