### ISSUE TITLE
Update the URL to display the test hash id

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#240]
When a test completes, we currently stay on the same page and display the results. It would be nice to update the page URL with the unique URL associated to this test (the same as under the "Share" button) so that it is easy to copy/paste (and share) the results.
Doing this might also give the possibility to navigate through the browser history as the URL is updated between each test.

**Comment by matsduf** [comment]
I think the current model gives a more stable impression. The URL for "this test" is available from the "Share" button.

**Comment by mattias-p** [comment]
The URL bar is the standard way to communicate URLs. It isn't helpful to force users to search for custom widgets with different looks, placements and behaviors in different web applications.

**Comment by pnax** [comment]
The idea is not to replace the "Share" button, just to update the URL with the proper URL associated to the test.

**Comment by blacksponge** [comment]
resolved by #257
