### ISSUE TITLE
Translation of buttons' tooltips/bubbles (Danish)

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#244]
PR #243 provides a mechanism for translation of the severity level buttons' tooltips/bubbles. Can you provide a translation for these lines? Either as a PR for da.json (when #243 is merged) or as a comment to this issue, but make sure to retain the format.
```
    "TOOLTIP_ALL": "Display all results",
    "TOOLTIP_CRITICAL": "Critical - means a very serious error.",
    "TOOLTIP_ERROR": "Error - means a problem that is very likely (or possibly certain) to negatively affect the function of the zone being tested, but not so severe that the entire zone becomes unresolvable",
    "TOOLTIP_INFO": "Info - is something that may be of interest to the zone's administrator but that definitely does not indicate a problem.",
    "TOOLTIP_NOTICE": "Notice - means something that should be known by the zone's administrator but that need not necessarily be a problem at all",
    "TOOLTIP_WARNING": "Warning - means something that will under some circumstances be a problem, but that is unlikely to be noticed by a casual user.",
```

**Comment by haarbo** [comment]
"TOOLTIP_ALL": "Vis alle resultater",
"TOOLTIP_CRITICAL": "Kritisk - betyder en meget alvorlig fejl.",
"TOOLTIP_ERROR": "Fejl - betyder et problem, der meget sandsynligt vil have en negativ indflydelse på den zone, der testes, men ikke så alvorlig, at hele zonen er fejlbehæftet",
"TOOLTIP_INFO": "Info - kan være af interesse for zonens administrator, men betyder ikke, at zonen indeholder et problem.",
"TOOLTIP_NOTICE": "Bemærk - betyder noget, der skal være kendt af zonens administrator, men det er ikke nødvendigvis et problem",
"TOOLTIP_WARNING": "Advarsel - betyder noget, der under visse omstændigheder vil være et problem, men som sandsynligvis ikke vil blive bemærket af den almindelige bruger.",

**Comment by matsduf** [comment]
@haarbo, thank you. The translations will be incorporated when #243 has been merged.

**Comment by matsduf** [comment]
Will be resolved by #248
