### ISSUE TITLE
Create a Contribution.md

### ISSUE THREAD

**Issue by pamasse** [zonemaster/zonemaster-gui#25]
Create a Contribution.md file which explain how works the development of the GUI (How build it, How update a value, etc.).

**Comment by sandoche2k** [comment]
Do you think this can be finished in 2019.1?

**Comment by pamasse** [comment]
@matsduf Shouldn't this file be in the main zonemaster repository?

**Comment by matsduf** [comment]
Yes, it does make sense to have that information in main repository, on the other hand the GUI code is handled so differently and the text here is meant for contributors of the GUI.

**Comment by pamasse** [comment]
But the contribution process is always the same in our repository: 
 - Fork
 - PR on develop
 - If accepted, merge

**Comment by pamasse** [comment]
Can be close ?

**Comment by matsduf** [comment]
If more aspects are found we will create a new issue.
