### ISSUE TITLE
Run from sub directory

### ISSUE THREAD

**Issue by Ressy66** [zonemaster/zonemaster-gui#250]
For the life of me I can not get this thing to run from a sub directory.

ie:
example.net/zonemaster/
example .net has stuff in there that needs to be served, we have a speed test and other tool, we used to run the old ruby thing in example.net/zopnecheck after lots of stuffing around re aliaseing it worked for years, but nothing we do will see zponemaster run from it, in fact it wants to overtake our existing content, I wont go into WTF it is so overly unnecessarily complex to install ina website, thats as frustrating as hell for non expert web/js experts, so I implore devs to keep us simpletons in mind when you advance your code in years to come.

ok, so anyone have any ideas?  
I have tried changing rewritebase from /  to /zonemaster/, tried different combos of the conditions. no matter what or where I put it, it expects  all files are in  /   so all we get is strings of 404's when we try us   /vhosts/example.net/html/zonemaster/

Hope someone can help.
cheers

**Comment by matsduf** [comment]
@Ressy66, if I understand it correctly, you want to run Zonemaster-GUI from e.g. https://example.com/zonemaster and 
https://example.com/zonemaster/domain_check instead of https://example.com/ and 
https://example.com/domain_check

You could easily create a subdomain for Zonemaster and run it from there, e.g. https://zonemaster.example.com/ and 
https://zonemaster.example.com/domain_check. Will that work for you?

**Comment by Ressy66** [comment]
We are trying to avoid subdomain wastage and keep our "tools area" under one domain so its all in one spot.  
This is why we chose to run it from a sub directory. I just dont get why this was written to make it so impossible for average system admin to do anything with other than do what its authors want, if I wanted that I'd be running microsoft servers, not linux :)

I have managed to get it to  run, and using apache aliasing I can get /result/.....   now,  but no matter what aliasing I try the faq just does not show up -  thats not overly important, but still, its a something thats broken, and I dont like it when things are not normal.

Also, I would now be hesitant to ever upgrade the GUI for risk of having to start fixing it all over again.

**Comment by matsduf** [comment]
We can take a look at it to see if it is possible to do what you request without too much changes. If you could provide us with what you have done to make it almost work it could help. If your installation is publicly available, please send the link. If you do not want to publish it here, you can go to my Github profile to find my email address.

**Comment by matsduf** [comment]
> Also, I would now be hesitant to ever upgrade the GUI for risk of having to start fixing it all over again.

That would be bad. For next release we have several nice updates for the GUI. They are already available in the develop branch or work-in-progress in pull requests.

**Comment by Ressy66** [comment]
Sorry, not sure how I missed this, but those ts files do not exist anywhere on the filesystem.

GUI was installed by           
wget https://github.com/zonemaster/zonemaster-gui/releases/download/v3.3.0/zonemaster_web_gui.zip

**Comment by Ressy66** [comment]
Ahhh that explains it :)

Will wait, it's the only thing not working, and a check of logs shows only 3 clicks on a faq that dont appear to be bots, so its not critical.

**Comment by matsduf** [comment]
This issue has been resolved by #252.
