### ISSUE TITLE
Ability to filter tests in history

### ISSUE THREAD

**Issue by blacksponge** [zonemaster/zonemaster-gui#251]
Now that the backend is going to correctly support delegated / undelegated filter for history, the GUI could implements the use of those filters in the history component.

From the discussion in https://github.com/zonemaster/zonemaster-backend/pull/826#discussion_r673154654 :

>  * In the normal case, the undelegated tests are unwanted because the are really not comparable with any other test unless the domain name and DS settings are equal.
> * By default only delegated tests are to be shown, with a buttons saying "all historic tests" and "only undelegated tests".

**Comment by matsduf** [comment]
I think this will improve the user experience of the GUI.

**Comment by matsduf** [comment]
zonemaster/zonemaster-backend#830 suggests an update so that the value is of "undelegated" is included if requested.

**Comment by pnax** [comment]
Done with #253
