### ISSUE TITLE
No progress meter in narrow window:

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#255]
When running a test with a narrow window no progress meter is shown. This is a screen show from a very narror window on a computer. If it is run on a mobile in portait position you will get the same affect.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/5430733/127773140-bfd09e8b-da18-4bc4-a55e-baa8b9fa2c0b.png">

------
Here is how it looks like when the window is wider, either on a computer (as here) or on a mobile in lanscape position:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/5430733/127772797-ed6daf67-7ac5-4867-bfdd-b4a2f2d2db48.png">

**Comment by blacksponge** [comment]
I remember having already investigating that but I don't remember if I already fixed it, I'll need to check with the develop branch

**Comment by blacksponge** [comment]
It does not seems to be completely fixed on develop either
![Screenshot 2021-08-04 at 09-55-33 Zonemaster](https://user-images.githubusercontent.com/19394895/128143790-4e795ac1-2060-46b5-ac00-34117151d889.png)

**Comment by matsduf** [comment]
Resolved by #259
