### ISSUE TITLE
Language change event not cleared when changing route

### ISSUE THREAD

**Issue by blacksponge** [zonemaster/zonemaster-gui#262]
When a component that watches the language changes (like the result or faq components) is loaded and then "unloaded" by navigating to a different route (like /domain_check) the event is never cleared. As a result changing the language again after visiting a result or the faq will still result in queries being made even though the event should not be watched anymore.

Step to reproduce :
1. Visit https://zonemaster.net/result/40047b0ede87b43a
2. Go to the faq page
3. Go to the domain check page
4. Change the language
5. By opening the dev tools you can see query to the api (`get_test_results`) and `gui-faq-{lang}.html` being made.

**Comment by matsduf** [comment]
Resolved by #265.
