### ISSUE TITLE
Some placeholders are not properly translated

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#277]
While testing #227, I found that the "Algorithm" and "Digest type" placeholders are not properly translated.

1. open the options
2. change the language
3. see all placeholders be translated except for the "Algorithm" and "Digest type"

Actually both are not placeholders:

https://github.com/zonemaster/zonemaster-gui/blob/867f12cd796e519d6531137af37c9317c6f6d976/src/app/components/form/form.component.html#L160

https://github.com/zonemaster/zonemaster-gui/blob/867f12cd796e519d6531137af37c9317c6f6d976/src/app/components/form/form.component.html#L185

**Comment by matsduf** [comment]
Can you see if the problem is browser dependent?

**Comment by pnax** [comment]
Indeed, it seems to be browser dependent. A fix would be to remove the "hidden" property.

**Comment by matsduf** [comment]
In what browser do you get the problem, and not get the problem, respectively? What effect would removing have?

**Comment by pnax** [comment]
I tested it with Firefox. And in the code, I can see the translation. It is just not rendered.
See #278

**Comment by pnax** [comment]
Closed by #278
