### ISSUE TITLE
Do not rely on external CSS when exporting results to HTML

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#279]
Currently we rely on an external bootstrap CSS file when exporting the results to HTML.
It would be nice to have the few style rules hard coded within the HTML exported file.

https://github.com/zonemaster/zonemaster-gui/blob/8062b2f779fcdea655c056fc324359dfb3788642/src/app/components/result/result.component.ts#L196

**Comment by matsduf** [comment]
Do we really need that many different export formats? I think we should focus on one or two and skip the rest. zonemaster-cli also, indirectly, offers export formats.

**Comment by pnax** [comment]
HTML is already a supported export format.

**Comment by matsduf** [comment]
But do we need it? Is it used in any noticable volume? All formats will need some maintenance. If we remove 1-2 formats that means less to maintain.

**Comment by pnax** [comment]
> Is it used in any noticable volume?

I think we won't have any answer to this question.

**Comment by pnax** [comment]
Closed with #308
