### ISSUE TITLE
Different page loading behaviors for domain_check and faq

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#282]
I'm getting a slightly different behaviors when switching between languages on /domain_check and /faq pages.

I'm using Firefox 94 on Fedora 35.

* On /domain_check each language is loaded only once no matter how many times I go back and forth between them.
* On /faq the languages are loaded every time I switch between them no matter if I've viewed that language before.

I'm not sure if this is a huge deal, but I wanted to make a note of it.

**Comment by blacksponge** [comment]
When you say language, is it the json file for the translation or the html file for the faq content?

**Comment by mattias-p** [comment]
It's the html files being reloaded every time. E.g. http://192.168.56.7/assets/faqs/gui-faq-fi.html.
The translation json only gets loaded once. E.g. http://192.168.56.7/assets/i18n/fi.json. And I just realized that if I reload the page this behavior resets.
Maybe this is a reasonable behavior?

**Comment by blacksponge** [comment]
The faq is loaded using a direct http call and not stored. The translation files are lazy loaded by the translation module and stored in memory. While not optimal this behaviour is known and expected. Also the faq files get cached and are only transmitted once per `/faq` visit which seems acceptable in my opinion.

**Comment by mattias-p** [comment]
That sounds good to me :)
