### ISSUE TITLE
Betterize display of results in GUI

### ISSUE THREAD

**Issue by tgreenx** [zonemaster/zonemaster-gui#340]
A number of improvements could be done in how we present the results of a Zonemaster test (https://zonemaster.fr/result/).

Here is a snippet of how it looks today:

![image](https://user-images.githubusercontent.com/96772376/195355196-34a8686d-9d8b-44af-ad04-65cf3f193432.png)

We have a list of expandable menus for each Module (Basic, Connectivity, Address, etc...). Within each list, we get a message comprised of three elements: the Module name, the log level, and the (translated) message ID.

Instead, we could have:

- A new menu that summarizes the outcome of a Test Case:
   - Instead of the Module name (e.g. BASIC), we could (should) have the Test Case identifier (e.g. BASIC00), with a link to the Test Case specification (in the form of an hyperlink and/or a tooltip).
   - Instead of the log level name directly, we could have some sort of visual indicator (i.e. icon; check box, cross, warning sign, etc...) indicating the general outcome of a Test Case. There would be one icon defined for each log level, using the color code used today, and the icon used to summarize the outcome of that Test Case would be the one from the worst level (e.g a Test Case with 5 messages, 4 being `INFO` and one being `WARNING` would only show the `WARNING` icon).
   - Instead of the (translated) message ID, we could have the Test Case description (e.g. "Domain name must be valid")

=> In that way, the user can immediately grasp the outcome of a Test Case within each Module, without having to "decode" each message ID one by one.

=> The current detailed message IDs would still be present, hidden by default, and similarly accessible by an expandable menu on a lower level.

- Within the expendable menu of each Module, we could have the count of each outcomes for each Test Case within that Module. Counts for log levels equal to 0 could be hidden by default to get a better view.

=> Similarly, this gives the user an immediate view of the outcomes in each Module.

I made a drawing to illustrate what I have just written above.

![zonemaster-gui-idea](https://user-images.githubusercontent.com/96772376/195381324-6c6ec59b-13f6-4038-bfa2-8367b37e88a3.jpg)

Ideas for improvement welcome. A draft implementation will soon follow.

**Comment by matsduf** [comment]
I like the idea. I also like that the test cases are more visible, and I think this could give some more structure to the output. And still keep the flexibility that we have in Zonemaster.

* The test case ID is already available in the JSON result blob for message.
* We probably have to rework the test case descriptions to make them more consistent and understandable, but that should not be too hard.
* All test case descriptions must be integrated in Zonemaster-Engine to make translation work for them too. It should be managable.
* The test case descriptions must be included in the JSON blob.
* We have to take into account that all test cases do not always output a message. Sometimes because the test case is not applicable, and sometimes because no message is outputted unless there something to comment. It should not be too much of a problem.

Please go ahead and further develop the idea! What is needed to be updated in Engine, Backend and GUI, respectively?

**Comment by blacksponge** [comment]
I started working on an implementation for this proposal (#341) feel free to comment even if it is still a draft so we have an early feedback.

Regarding the points you mentioned,

> The test case ID is already available in the JSON result blob for message.

Currently only the module name and severity level are available in the message from backend. I opened https://github.com/zonemaster/zonemaster-backend/pull/1055 to add the testcase as well.

> All test case descriptions must be integrated in Zonemaster-Engine to make translation work for them too. It should be managable.
> The test case descriptions must be included in the JSON blob.

For now I integrated the test case descriptions as GUI translated string, either way would work, do we have a need for having the test case description available from engine? Also by having them in the GUI translation file we don't need to send them in the JSON response from backend.

> We have to take into account that all test cases do not always output a message. Sometimes because the test case is not applicable, and sometimes because no message is outputted unless there something to comment. It should not be too much of a problem.

In the current implementation a test case without message is simply not displayed, which I think is an acceptable behaviour.

**Comment by matsduf** [comment]
> > All test case descriptions must be integrated in Zonemaster-Engine to make translation work for them too. It should be managable.
> > The test case descriptions must be included in the JSON blob.
> 
> For now I integrated the test case descriptions as GUI translated string, either way would work, do we have a need for having the test case description available from engine? Also by having them in the GUI translation file we don't need to send them in the JSON response from backend.

It scales better if Engine is the only place where we have to update when there is an updated or new test case. Furthermore, we will ensure that the version of the description is the same as the version of the messages. It will pay off in long run to have them in Engine.

**Comment by matsduf** [comment]
Let me clarify. Say that Engine and GUI from v2024.1 have been installed. Then v2024.2 comes out with added and updated test cases. If the test case descriptions live in GUI then you have to update GUI every time Engine has added test cases or updated test case descriptions. If we, in this case, only update Engine to v2024.2 then the presentation would be a mix of two versions.

**Comment by blacksponge** [comment]
See answer at https://github.com/zonemaster/zonemaster-gui/pull/341#issuecomment-1277659055.

**Comment by tgreenx** [comment]
Resolved by #341
