### ISSUE TITLE
Wrong name in "Program versions"

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#351]
The "Program version" link gives a pop-up with the versions of the Zonemaster components. The names are abbreviated "Ldns", "Engine", "Backend" and "Gui". None of the abbreviations are without problem, but worst is "Ldns" since there is another software "LDNS". I suggest that we
1. Do not use abbreviations so that we match what the components are called elsewhere.
2. Use the case setting.

I suggest:
```
Zonemaster-LDNS v2.2.2
Zonemaster-Engine v4.5.1
Zonemaster-Backend v9.0.1
Zonemaster-GUI v3.6.1
```

![image](https://user-images.githubusercontent.com/5430733/198323928-259f8c2e-6154-4ec7-aa5c-58b149e7b53b.png)

**Comment by blacksponge** [comment]
I will be fixing this in #341. Regarding the version number, the code in GUI explicitly remove the leading `v` , are you suggesting we add it back? (given that this is not consistent amongst our different repos).

**Comment by matsduf** [comment]
I think we should be consistent, and in most cases the version is with "v" but as you say it is not consistent. Why the leading "v" is removed I do not understand.

**Comment by blacksponge** [comment]
> Why the leading "v" is removed I do not understand.

I think it was removed to be consistent and only give the version number.

**Comment by matsduf** [comment]
The update in #341 is good enough.
