### ISSUE TITLE
Tries to fetch from parent zone even if domain has not been given

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#39]
If you are in the pre-delegated domain mode and leave the domain name field empty and press "fetch data from parent zone" the gui will request the backend for "get_data_from_parent_zone" with empty domain. 

Maybe it relates to issue #38.

**Comment by sandoche2k** [comment]
Issue related to #40

**Comment by matsduf** [comment]
Solved by #41.
