### ISSUE TITLE
No error message when trying to fetch for a non-domain

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#40]
If you in pre-delegated domain mode enters a domain that does not exist and presses "fetch data from parent zone" then the gui will not get any data back from the backend but no error is shown.

Maybe it relates to issues #38 and #39.

**Comment by pamasse** [comment]
@matsduf You would like to see an warning (in orange) message like that : "No parent zone found" ?

**Comment by matsduf** [comment]
Rather "The domain does not exist", or "There is no delegation for the zone.". If you go to "pre-delegated domain" and enter "namn.se" and press "fetch data from parent zone" then the parent zone .SE does exist, but there is no delegation for namn.se.

@sandoche2k, please review!

**Comment by sandoche2k** [comment]
@pamasse the fix is there. But it is not easily visible to a non suspecting user. Maybe it should have been a pop up. Try it here http://vps323914.ovh.net/domain_check

**Comment by matsduf** [comment]
I tried http://vps323914.ovh.net/domain_check. The warning that there is no delegation disappears by itself. It is better if the user has to click "ok" or something.

(A second thing is that pre-delegated (undelegated) testing is hidded behind "Options", which I think is less optimal. It should be visiable.)

**Comment by matsduf** [comment]
Solved #42
