### ISSUE TITLE
Update translation of GUI strings to Norwegian and Spanish

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#421]
Most strings are translated as they should, but the the following terms have been added late. If you can provide translation to your respective language of those as a comment to this PR I will add them to the XLF files.

Used as alternative text for spoken rendering for visually impaired people for "«" etc in history pop-up window:

```
First
Previous
Next
Last
```

To be displayed in the footer:

```
Source code
Documentation
```

**Comment by samisalmensuo** [comment]
FI:

First
Ensimmäinen

Previous
Edellinen

Next
Seuraava

Last
Viimeinen

Source code
Lähdekoodi

Documentation
Dokumentaatio

**Comment by samisalmensuo** [comment]
Sorry wrong language :D

**Comment by huguei** [comment]
Follows spanish translation.

I'm not sure what type of graphical interface is. I'm assuming "male gender" in translation, which works for buttons or listings, but if it were something referring to "screens" for example, it'll be best using female gender.

- First: Primero
- Previous: Anterior
- Next: Siguiente
- Last: Último
- Source code: Código fuente
- Documentation: Documentación

**Comment by matsduf** [comment]
> ```
> First
> Previous
> Next
> Last
> ```

@blacksponge, where do we find the terms above? I do not find it in the GUI. See the comment from @huguei above.

**Comment by blacksponge** [comment]
There are used as alt text (e.g. for screen readers) in history pagination.

![Screenshot 2023-05-23 at 09-04-08 ppsfleet navy · Zonemaster](https://github.com/zonemaster/zonemaster-gui/assets/19394895/d13f397e-4062-4bab-8a43-de78ae85fb59)

![Screenshot from 2023-05-23 09-05-21](https://github.com/zonemaster/zonemaster-gui/assets/19394895/f4f9bddb-6ab5-41b0-a393-bcf287d827ac)

**Comment by matsduf** [comment]
I guess you mean tooltip for "«" etc. I cannot see "First" etc when testing in Firefox and Chrome.

**Comment by repperille** [comment]
NB:

First
Først

Previous
Tidligere

Next
Neste

Last
Siste

Source code
Kildekode

Documentation
Dokumentasjon

**Comment by huguei** [comment]
@matsduf Yes, it's "window" or "screen", so its feminine in both cases.
There're two changes, new translation is:

 - First: Primera
 - Previous: Anterior
 - Next: Siguiente
 - Last: Última
 - Source code: Código fuente
 - Documentation: Documentación

Thanks.

**Comment by matsduf** [comment]
@huguei, please review #423.

**Comment by matsduf** [comment]
Updated by #423
