### ISSUE TITLE
Tooltip and dropdown content outside of reach on small device

### ISSUE THREAD

**Issue by pnax** [zonemaster/zonemaster-gui#427]
It would be nice to avoid displaying tooltip and dropdown content outside of the screen on small device.

### Footer version tooltip:
![zm-gui-footer](https://github.com/zonemaster/zonemaster-gui/assets/70589067/a4ad96c7-471c-4c65-a309-494581b9f95d)

### Export dropdown:
![zm-gui-export](https://github.com/zonemaster/zonemaster-gui/assets/70589067/0acb1e8c-ca2e-433b-a1fa-7218048f1669)

### Context:
v2023.1 release testing:
* https://github.com/zonemaster/zonemaster-gui/pull/403#issuecomment-1570069150
* https://github.com/zonemaster/zonemaster-gui/pull/413#issuecomment-1570421894

**Comment by blacksponge** [comment]
Fixed with 2023.2
