### ISSUE TITLE
Modules names should not be uppercase

### ISSUE THREAD

**Issue by blacksponge** [zonemaster/zonemaster-gui#437]
The name of the module (as well of test cases for that matter) are uppercase. This cause screen readers to read them like acronyms (C-O-N-S-I-S-T-E-N-C-Y) instead of words (Consistency).
I open the issue here but I think the fix should come from engine, this is were the current strings come from, so that we avoid hacks in GUI to fix that.

**Comment by matsduf** [comment]
I am not against the change, but I disagree that the fix should come from Engine or GUI. The change should come in the specification. We should define what it should be there, and then implement it in different places. The following document could be a start: https://github.com/zonemaster/zonemaster/blob/master/docs/internal/templates/specifications/tests/TestCaseIdentifierSpecification.md

**Comment by blacksponge** [comment]
I said Engine because in the current implementation that is where they are coming from.
I guess it would be better if the spec is changed.

**Comment by matsduf** [comment]
My point is that we should not change in Engine before we specify the format in the specification. And with specification I do not mean each test case specification, but a specification of how those should be written.

**Comment by blacksponge** [comment]
Okay I will make a proposal.

**Comment by blacksponge** [comment]
Fixed with 2023.2
