### ISSUE TITLE
Apache modules on CentOS

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#55]
On Debian it is documentet that Apache modules proxy, proxy_http and rewrite are to be enabled.

On FreeBSD that is missing, but added by PR #54.

On CentOS that is still missing, or is that not needed?

**Comment by sandoche2k** [comment]
I followed the install instructions (for CentOS) and it was working for me.

**Comment by matsduf** [comment]
It would be surprising if those module are enabled by default on CentOS. Are you sure that you did not update the Apache configuration file?

**Comment by sandoche2k** [comment]
I just followed the install instructions on a clean installation
