### ISSUE TITLE
Domain test cannot be reset

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#58]
Installation from develop branch, commit fc3be71.

If I run a test of a domain and then want to test another, there is no obvious way getting an empty form. If I click "domain check" nothing happens. I could manually erase the domain field, but the result is still there. 

The work-around now is to click on "FAQ" and then "domain check", but that feels awkward.

**Comment by pamasse** [comment]
We could add a button at the same place that we display the percentage during the test.
This button will be used to clean only the domain name input and not the "advanced options".
For them, we can add a reset button below the actual "Fetch parent zone" button.

**Comment by matsduf** [comment]
You need to be able to go back to clean state including removed advanced options.

**Comment by pamasse** [comment]
@pamasse 
add a reset button in the options
reset domain input after a test
