### ISSUE TITLE
"Pre-delegated domain" is not a good title

### ISSUE THREAD

**Issue by aabdnn** [zonemaster/zonemaster-gui#6]
In the GUI, the "Pre-delegated domain" title isn't very nice. I think it would look better as:

Pre-delegation check

This is because the check is *exactly* that: a check of a domain's setup before (re)delegation.

**Comment by sandoche2k** [comment]
@pamasse i agree with @aabdnn. Please correct and make a commit.

**Comment by sandoche2k** [comment]
@pamasse please update and modify  "Pre-delegated domain" to "Pre-delegation check". We should also modify the translation accordingly @matsduf for Danish and Swedish?

**Comment by matsduf** [comment]
@sandoche2k, we should look at it.

Is "pre-delegation check" the right phrase? In the FAQ it it referred to as "undelegated domain test".

**Comment by sandoche2k** [comment]
I would vote for pre-delegation check. "undelegated domain test" seems to me that i am testing a domain that will not be delegated. Rather, 99.9% of the use case will be to test before the domain is delegated.

**Comment by matsduf** [comment]
Pre-delegated sound like a domain that is not yet delegated, but the test can be run on delegated domains with the same or new data. 

I do not agree on the use case. If the first delegation fails then you can just update and correct without any issues. When you have a domain in production you want to make sure that the new data is correct. That is what the FAQ points out.

Normal test is "Domain check". The other could be "Domain pre-check". That "pre" could be pre-delegation or pre-redelegation.

Or maybe, "Check your domain" and "Pre-Check your domain", and then a short explanation of what "pre-check" does.

**Comment by sandoche2k** [comment]
@pamasse close?
