### ISSUE TITLE
Broken test result links

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-gui#67]
The URL scheme for test results has changed in an incompatible way. This breaks all existing links to historical test results. Those links are often used in our issue tracker.

A conceivable fix is to go through our issue trackers and update all links, but that's a tedious task and would not fix any links that are outside of our issue trackers.

Another conceivable fix is to just revert to the old URL scheme, but that would break all links created with the new URL scheme.

An adequate solution would involve redirects from one of the URL schemes to the other.

**Comment by pamasse** [comment]
Duplicate #73 ?

**Comment by pamasse** [comment]
Fix by #71
