### ISSUE TITLE
redirect all history from test to result

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-gui#71]
Earlier, the links for the test results were having a "test" folder : 
https://zonemaster.net/test/8cdea95024d8c8b9
Now, it has been moved to the "result" folder : 
https://zonemaster.net/result/8cdea95024d8c8b9

The issue is that if we click on the links containing test results in old issues, we do have a no page found. Therefore the old links should be automatically redirected to the appropriate link.
That is the test folder should be automatically redirected to result folder.

**Comment by matsduf** [comment]
Will be resolved by #73
