### ISSUE TITLE
Improve automatic testing (Align documentations and automated tests / Mock backend)

### ISSUE THREAD

**Issue by pamasse** [zonemaster/zonemaster-gui#83]
The set of actuals tests implemented are based on the previous zonemaster-gui in perl.
We should review the documentations about functionnal test requirements of the GUI ([functional test requirements](https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/requirements/GUI-Functional-Test-Requirements.md)) and then implements all tests.

In order to only test frontend and to be able to implement new backend api response before it's installation one solution is to implement a fake backend. The response of the fake backend will be based on the api documentation. 
[Ng-apimock](https://github.com/mdasberg/ng-apimock) could be a solution. We also could do a simple nodejs backend. 

- [x] Review [functional test requirements](https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/requirements/GUI-Functional-Test-Requirements.md)
- [x] Mock Backend 
- [x] Implement tests

**Comment by matsduf** [comment]
@pamasse, is this resolved by #84?

**Comment by pamasse** [comment]
Yes !!
