### ISSUE TITLE
Update the French translation of the FAQ

### ISSUE THREAD

**Issue by matsduf** [zonemaster/zonemaster-gui#89]
The French version of the FAQ should be a translation of the English version. When the update of the English version has been merged (#88), the French needs updates.

**Comment by matsduf** [comment]
@sandoche2k, will anyone check this?

* It refers to us as "IIS". It should be "The Swedish Internet Foundation".
* There is a broken link, https://zonemaster.net/test/18281

**Comment by sandoche2k** [comment]
The assignee is @pamasse

**Comment by matsduf** [comment]
@vlevigneron, could  you take a look at this for v2020.1?

**Comment by matsduf** [comment]
Resolved by #164
