### ISSUE TITLE
IDN does not work with CentOS7 in PSQL

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-gui#93]
http://vps323915.ovh.net/domain_check (Test with café.fr)

**Comment by matsduf** [comment]
@sandoche2k, what is the relation between this and https://github.com/zonemaster/zonemaster-backend/issues/570? The latter has a proposed solution in https://github.com/zonemaster/zonemaster-backend/issues/571

**Comment by sandoche2k** [comment]
Only if i Test, I will know that there is a solution

**Comment by pamasse** [comment]
Can we close since it does not concern the GUI ?

**Comment by sandoche2k** [comment]
yes
